[package]
name = "plygui-qt"
version = "0.0.1"
authors = ["Serhii Plyhun <snuk188@gmail.com>"]
edition = "2018"

[lib]
name = "plygui_qt"
path = "src/lib.rs"

[dependencies]
plygui-api = {version = "0.0.1", path = "../plygui/api"}
qt_core = {package = "qt_core_6", path = "../../ritual-workspace/qt_workspace/out/qt_core_6"}
qt_gui = {package = "qt_gui_6", path = "../../ritual-workspace/qt_workspace/out/qt_gui_6"}
qt_widgets = {package = "qt_widgets_6", path = "../../ritual-workspace/qt_workspace/out/qt_widgets_6"}
qt_core_custom_events = {path = "../qt_core_custom_events"}
lazy_static = {version = "~1.4"}
libc = {version = "~0.2"}

[features]
markup = ["plygui-api/markup"]
type_check = ["plygui-api/type_check"]
default = ["type_check"]